name: Build App

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build App
        run: bun run build

      - name: Deploy App
        run: bun run deploy
