name: Monthly Cleanup Script

# This will run the script on the first day of every month
# For more information, see: https://crontab.guru/#0_0_1_*_*
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run-script:
    name: Setup Python and run script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run script
        run: python Archive-Repos-Task.py
