name: Create a new Repo

on:
  workflow_dispatch:
    inputs:
      RepoName:
        description: 'Name of the repo'
        required: true
        type: string

      RepoTeam:
        description: 'The team that owns the repo.'
        required: true
        type: choice
        options:
          - Platform
          - Frontend
          - Backend
          - DevOps
          - QA
          - Design

      RepoDescription:
        description: 'An optional description of the repo.'
        required: false
        type: string

      RepoTopics:
        description: 'An optional list of topics for the repo, separated by commas.'
        required: false
        type: string

      RepoType:
        description: 'The type of repo to create.'
        required: true
        type: choice
        default: Elysia
        options:
          - Bun
          - Elysia

jobs:
  create:
    name: Create a new Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --cwd ./New-Repo-Task

      - name: Run Create Script
        run: bun run ./New-Repo-Task/index.ts
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO_NAME: ${{ inputs.RepoName }}
          REPO_TEAM: ${{ inputs.RepoTeam }}
          REPO_DESCRIPTION: ${{ inputs.RepoDescription }}
          REPO_TOPICS: ${{ inputs.RepoTopics }}
          REPO_TYPE: ${{ inputs.RepoType }}
          # REPO_OWNER: ${{ github.repository_owner }}
